config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pics
  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_action :get_pic, only: [:show, :edit, :update, :destroy]

    def index
        @pics = Pic.all.order("created_at DESC")
    end 
    def show 
        @pic = Pic.find(params[:id])
    end
    def new 
        @pic = current_user.pics.build
    end
    def create 
        @pic = current_user.pics.build(pic_params)
        if @pic.save 
            flash[:notice] = "Picture was posted"
            redirect_to @pic
        else 
            render 'new'
        end
    end
    def edit 
    end
    def update 
        if @pic.save 
            flash[:notice] = "Picture was updated"
            redirect_to @pic
        else 
            render 'edit'
        end
    end
    def destroy
        @pic.destroy
        redirect_to root_path
    end
    private
    def pic_params
        params.require(:pic).permit(:title, :description)
    end
    def get_pic
        @pic = Pic.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Istagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to "Istagram", root_path, :class=>"navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo03">  
        <% if user_signed_in?  %>
          <ul class="navbar-nav mt-2 mt-lg-0">
            <li class="nav-item active">
              <%= link_to "Home", root_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Gram It", new_pic_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Settings", edit_user_registration_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, :class => "nav-link"%>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to "Sign up", new_user_registration_path%></li>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path%></li>
          </ul>
        <% end %>
      </div>

    </nav>
    <div class="container">
      <% flash.each do | name, msg | %>
        <div class="alert alert-info">
          <p> <%= msg %></p>
        </div>
      <%end%>
      <%= yield %>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pics/_form.html.haml
= simple_form_for(@pic, html: { class: 'form-inline', multipart: true }) do |f|
    - if @pic.errors.any? 
        #errors
            %h2
                = "#{pluralize(@pic.errors.count, 'error', {})} prevented this image from saving"
            %ul
                - @pic.errors.full_message.each do |msg| 
                    %li= msg 
    .form-group 
        = f.input :title, input_html: { class: 'form-control'}
    .form-group 
        = f.input :description, input_html: { class: 'form-control'}
    .btn.btn-info
        = f.button :submit

app/views/pics/edit.html.haml
%h1 edit page
= render 'form'
= link_to('Cancel', pic_path)

app/views/pics/index.html.haml
%h1 index for pics
= link_to('Gramit', new_pic_path)
- @pics.each do |pic| 
    %h2= link_to pic.title, pic
    %p= pic.description
    = time_tag(pic.created_at, {})

app/views/pics/new.html.haml
%h1 new Pic page 

= render 'form' 

app/views/pics/show.html.haml
%h1 this is the pic#show

%h3= @pic.title
%p= @pic.description
%p= "pic by #{@pic.user.email}"
= link_to('Edit', edit_pic_path)
= link_to('Delete', pic_path, method: :delete, data: {confirm: "are you sure"} )
= link_to('All pics', pics_path)